### ISSUE TITLE
Need to fix CSS on desktop

### ISSUE THREAD

**Issue by aadinesarkar** [aryanpingle/Mess-Menu#2]
![image](https://user-images.githubusercontent.com/83160024/202635194-0eeca979-841e-4ffe-b2b3-f14b4708e32c.png)

Not sure how to fix this

**Comment by aryanpingle** [comment]
Yeah lol, I think I lazily put `75vh` or some arbitrary height for all of them, didn't think there'd be so many items. Using `display: grid` with equal sized columns might do the trick.

**Comment by Aphievel** [comment]
Ok I'll take a look at it

**Comment by Aphievel** [comment]
![image](https://user-images.githubusercontent.com/83160024/202708512-f0357a22-886b-40ad-b49d-518ce054208b.png)

How's this?

**Comment by aryanpingle** [comment]
Issue seems to be fixed, thanks @aadinesarkar and @akshatgokul
